version: '3.8'
services:
  flamenco-monitor:
    build: .
    container_name: flamenco-monitor
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
